In [7]:
import torch
import pandas as pd
import numpy as np

In [35]:
a = [torch.arange(48).reshape((2, 4, 6)) * i for i in range(1, 14)]
a

[tensor([[[ 0,  1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10, 11],
          [12, 13, 14, 15, 16, 17],
          [18, 19, 20, 21, 22, 23]],
 
         [[24, 25, 26, 27, 28, 29],
          [30, 31, 32, 33, 34, 35],
          [36, 37, 38, 39, 40, 41],
          [42, 43, 44, 45, 46, 47]]]),
 tensor([[[ 0,  2,  4,  6,  8, 10],
          [12, 14, 16, 18, 20, 22],
          [24, 26, 28, 30, 32, 34],
          [36, 38, 40, 42, 44, 46]],
 
         [[48, 50, 52, 54, 56, 58],
          [60, 62, 64, 66, 68, 70],
          [72, 74, 76, 78, 80, 82],
          [84, 86, 88, 90, 92, 94]]]),
 tensor([[[  0,   3,   6,   9,  12,  15],
          [ 18,  21,  24,  27,  30,  33],
          [ 36,  39,  42,  45,  48,  51],
          [ 54,  57,  60,  63,  66,  69]],
 
         [[ 72,  75,  78,  81,  84,  87],
          [ 90,  93,  96,  99, 102, 105],
          [108, 111, 114, 117, 120, 123],
          [126, 129, 132, 135, 138, 141]]]),
 tensor([[[  0,   4,   8,  12,  16,  20],
          [ 24,  28,  32,  3

In [36]:
b = a[1][:, 0, :].unsqueeze(1)
b, b.shape

(tensor([[[ 0,  2,  4,  6,  8, 10]],
 
         [[48, 50, 52, 54, 56, 58]]]),
 torch.Size([2, 1, 6]))

In [4]:
labels = pd.read_csv("D:\python_code\paper\data\\test_label2.csv")["idx"]
labels

0       11
1       17
2       12
3        1
4       14
        ..
2043    20
2044    20
2045    26
2046     9
2047     5
Name: idx, Length: 2048, dtype: int64

In [8]:
labels_ids = np.array([x for x in labels])

In [10]:
labels_ids.to("cpu")

AttributeError: 'numpy.ndarray' object has no attribute 'to'